<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ServiceBatch extends Model
{
    use HasFactory;

    /**
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'service_id',
        'batch_reference',
        'total_submitted',
        'accepted_count',
        'rejected_count',
        'unit_price',
        'total_charged',
        'submission_notes',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'total_submitted' => 'integer',
            'accepted_count' => 'integer',
            'rejected_count' => 'integer',
            'unit_price' => 'decimal:2',
            'total_charged' => 'decimal:2',
        ];
    }

    /**
     * The user who submitted the batch.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The service this batch was submitted for.
     */
    public function service(): BelongsTo
    {
        return $this->belongsTo(Service::class);
    }

    /**
     * The individual requests generated by this batch.
     */
    public function requests(): HasMany
    {
        return $this->hasMany(ServiceRequest::class, 'batch_id');
    }

    /**
     * Formatted total charged in Naira.
     */
    public function getFormattedTotalChargedAttribute(): string
    {
        return '₦' . number_format((float) $this->total_charged, 2);
    }

    /**
     * Consistent 8-digit integer identifier for the batch.
     */
    public function getBatchNumberAttribute(): string
    {
        if (is_numeric($this->batch_reference) && strlen((string) $this->batch_reference) === 8) {
            return (string) $this->batch_reference;
        }
        return str_pad((string) (10000000 + ($this->id % 90000000)), 8, '0', STR_PAD_LEFT);
    }
}
